#!/bin/bash

# title: compile.sh
# author: twab
# description: compile thesis.tex -> thesis.pdf

# required files:
# * thesis.tex 
# * dukethesis.cls
# * bibliography.bib
# * Any additional files sourced by thesis.tex!

# compiling latex can be messy! 
#pdflatex -shell-escape thesis.tex && \
#		bibtex thesis.aux && pdflatex -shell-escape thesis.tex

# if you don't use minted, then compilation becomes very easy using tectonic:
tectonic thesis.tex
