#!/bin/bash

# title: compile.sh
# author: twab
# description: compile thesis.tex -> thesis.pdf

# required files:
# * thesis.tex 
# * dukethesis.cls
# * bibliography.bib
# * Any additional files sourced by thesis.tex!

# latex compilation is simple using tectonic:
tectonic thesis.tex
